version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: OpenCV
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: make@makeitnow.in
      PGADMIN_DEFAULT_PASSWORD: OpenCV
    ports:
      - 8086:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  nginx:
    build:
      context: ./Dockerfiles
      dockerfile: nginx_files
    expose:
      - 80
    ports:
      - 8080:80

  flask:
    build:
      context: ./Dockerfiles
      dockerfile: flask_files
    expose:
      - 5000
    ports:
      - 9393:5000
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
