version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: OpenCV
    ports:
      - 5432:5432
    volumes:
      - ../pg-data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: make@makeitnow.in
      PGADMIN_DEFAULT_PASSWORD: OpenCV
    ports:
      - 8086:80
 
  nginx:
    build:
      context: ./Dockerfiles
      dockerfile: nginx_files
    expose:
      - 80
    ports:
      - 8080:80
  
  flask:
    build:
      context: ./Dockerfiles
      dockerfile: flask_files
    expose:
      - 5000
    ports:
      - 9393:5000


